### ISSUE TITLE
setters and getters with multiple variables

### ISSUE THREAD

**Issue by gaurav1780** [delebota/java-generator#10]
when multiple variables are declared within a single statement like "private int length, breadth, height;", creating getters and setters only creates getter and setter for the first variable. But if declared separately, like "  private int length;
  private int breadth;
  private int height;", it creates getters and setters for all of them.

**Comment by gaurav1780** [comment]
thanks mate :)

**Comment by delebota** [comment]
Added support for this in version 2.2.0, should be live now!
