### ISSUE TITLE
generate setters and getters - maps

### ISSUE THREAD

**Issue by concon121** [delebota/java-generator#11]
Has problems generating the getters and setters for Map<Object, Object>:

    private Map<String, List<HaulageAddress>> pickUpLocations;
    private HaulageAddress dropOffLocation;
    
    
	/**
	* Returns value of g
	* @return
	*/
	public Map<Strin getG() {
		return g;
	}

	/**
	* Sets new value of g
	* @param
	*/
	public void setG(Map<Strin g) {
		this.g = g;
	}

    

	/**
	* Returns value of dropOffLocation
	* @return
	*/
	public HaulageAddress getDropOffLocation() {
		return dropOffLocation;
	}

	/**
	* Sets new value of dropOffLocation
	* @param
	*/
	public void setDropOffLocation(HaulageAddress dropOffLocation) {
		this.dropOffLocation = dropOffLocation;
	}

**Comment by delebota** [comment]
The above commit doesn't appear to fix the issue according to my tests, I'll look into it now.

**Comment by delebota** [comment]
Fixed in version 2.2.0
