### ISSUE TITLE
"No variables were found." when creating a constructor to an empty class

### ISSUE THREAD

**Issue by renanliberato** [delebota/java-generator#13]
When using the _create constructor_ command in an empty class (whithout properties)  an error is showed and the second constructor is generated without the closing parentheses. Example:

![javaconstructorerror](https://cloud.githubusercontent.com/assets/15313802/20031430/72d7e37e-a35e-11e6-94ef-27dbd4ff00e2.png)
![examplejavaconstructorerror](https://cloud.githubusercontent.com/assets/15313802/20031431/75342722-a35e-11e6-8c4b-1ec6d4bf4d2a.png)

**Comment by delebota** [comment]
Thanks, I will take a look.
