### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kendrickwilson** [delebota/java-generator#6]
can you have the getters and setters next to each other...

It would be nice to have a ctlr-alt-b (bean)

<hr/>
(no constructor is present)
<pre>
class AClass {
 private int a;
}
</pre>
transform into 

<pre>
class AClass {
 private int a;
 
 public AClass () {}

 public void setA(int a) {this.a=a;  } 
 public int getA() {return a;}
}
</pre>

<hr/>
(constructor is present)
<pre>
class AClass {
 private int a;
 private int b; 

 public AClass () {}

 public void setA(int a) {this.a=a;  } 
 public int getA() {return a;}
}
</pre>
transform into (if not constructor is present)
<pre>
class AClass {
 private int a;
 private int b;

 public AClass () {}

 public void setA(int a) {this.a=a;  } 
 public int getA() {return a;}

 public void setB(int b) {this.b=b; } 
 public int getB() {return b;}
}
</pre>

**Comment by delebota** [comment]
I have been thinking about combining get/set generation so they will be next to each other.

I haven't thought about doing it all (except toString) at once but it would be easy to implement.

**Comment by Michael-Thibault** [comment]
Preferably as an option for those who prefer having getters and setters grouped together.

**Comment by delebota** [comment]
Fixed in 2.1.0 which is now published!
