### ISSUE TITLE
Feature Request: Option to Use "this" for Getters

### ISSUE THREAD

**Issue by Michael-Thibault** [delebota/java-generator#8]
Personal preference really. Would be nice to have an option for getters to have this put in-front of the variables/references in the return statement. I know it's redundant and it's implied anyway, but for clarity I usually do it.

**Comment by nishtahir** [comment]
I added a setting for this. Should be included whenever my pull request is accepted

**Comment by Michael-Thibault** [comment]
Well then, thanks for that. :)

**Comment by delebota** [comment]
Fixed in 2.1.0 which is now published!
